### ISSUE TITLE
Feature request: Only show block name on selection and/or hover

### ISSUE THREAD

**Issue by maddisondesigns** [kalimahapps/Editor-Block-Outline#1]
Thanks for creating this plugin. It definitely makes Gutenberg more usable.

It would be great if there was an option to only show the block names on hover and/or selection. At the moment, when there's blocks within blocks, the block names tend to sit on top of each other which makes them unreadable.

Thanks.

<img width="1557" alt="screenshot_682" src="https://user-images.githubusercontent.com/2078245/125892425-5cbedcc4-d79e-474b-927d-6290b221f0c8.png">

**Comment by abdul-alhasany** [comment]
Hi 
Thanks for the feedback.

I will try to implement this feature, I think it will be useful. The issue is I try to implement features that depending less on JS and more on CSS. This feature will probably require some event handling in JS.

In the meantime, you can adjust the outline padding for each element. It is not ideal but I guess will do.

**Comment by abdul-alhasany** [comment]
@maddisondesigns I released a new version 1.1 including the change that you requested. Please let me know if it works as expected.

**Comment by maddisondesigns** [comment]
That works beautifully! Thank you for adding that change, and for doing  it so quickly too. It's much appreciated 🙏 🙂

**Comment by abdul-alhasany** [comment]
Glad it resolved the issue. 

I have another WordPress plugin that I would love some testing or feedback if you are interested.

https://wordpress.org/plugins/nashaat-activity-log/

**Comment by maddisondesigns** [comment]
Sure no probs. Have just installed it on a test site so as to let it gather some logs entries
