### ISSUE TITLE
Outlines for 6.5.2

### ISSUE THREAD

**Issue by michaelprflores** [kalimahapps/Editor-Block-Outline#6]
Hi, I saw that the latest release 1.3.1 was to test for 6.5. I tried 1.3.1 and 1.3.0 and can't get any of the outlines to appear on my WordPress 6.5.2 installation. Curious if you all ran into any issues. Thanks.

**Comment by abdul-alhasany** [comment]
You are right. Somehow the plugin works on existing installation but not fresh ones. When I tested it on a fresh installation the plugin did not work, and the reason is that Gutenberg editor has been iframed.

Anyway, I updated the plugin and tested with existing and fresh installation again to make sure it is working as expected. Try version 1.3.2 and let me know.

**Comment by michaelprflores** [comment]
Hi @abdul-alhasany Thank you! It's working now.
![Screenshot 2024-04-12 at 12 46 13 PM](https://github.com/kalimahapps/Editor-Block-Outline/assets/80967246/7be7d182-1165-49c6-976a-842c4769d5fb)
